perform_cut:
  name: Perform Cut
  description: Execute a cut transition on the ATEM switcher
  
set_program_input:
  name: Set Program Input
  description: Change the program input on the ATEM switcher
  fields:
    input:
      name: Input Number
      description: The input number to switch to (1-20 typically)
      required: true
      example: 1
      selector:
        number:
          min: 1
          max: 20
          mode: box

set_preview_input:
  name: Set Preview Input
  description: Change the preview input on the ATEM switcher
  fields:
    input:
      name: Input Number
      description: The input number to set as preview (1-20 typically)
      required: true
      example: 2
      selector:
        number:
          min: 1
          max: 20
          mode: box

auto_transition:
  name: Auto Transition
  description: Execute an auto transition on the ATEM switcher